### ISSUE TITLE
ipykernelが追加されていなかった

### ISSUE THREAD

**Issue by sugimochi97** [mochi-science/arXiv_bot#7]
ipykernelが追加されていなかった

_Originally posted by @sugimochi97 in https://github.com/mochi-science/arXiv_bot/issues/1#issuecomment-2360726898_

**Comment by aries2004-bit** [comment]
maybe this will help
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by sugimochi97** [comment]
追加した
